
import { Product } from './types';

export const MOCK_PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Aether Pods Pro',
    description: 'Next-generation wireless audio with spatial depth and noise cancellation.',
    price: 249.99,
    category: 'Electronics',
    image: 'https://picsum.photos/seed/pods/600/600',
    rating: 4.8,
    reviews: 1240,
  },
  {
    id: '2',
    name: 'Lumina Smart Watch',
    description: 'Track your vitality with sapphire glass and AMOLED brilliance.',
    price: 399.00,
    category: 'Electronics',
    image: 'https://picsum.photos/seed/watch/600/600',
    rating: 4.7,
    reviews: 890,
  },
  {
    id: '3',
    name: 'Terra Leather Backpack',
    description: 'Sustainable artisan leather crafted for the modern nomad.',
    price: 185.00,
    category: 'Fashion',
    image: 'https://picsum.photos/seed/bag/600/600',
    rating: 4.9,
    reviews: 530,
  },
  {
    id: '4',
    name: 'Zenith Mechanical Keyboard',
    description: 'Tactile precision with customizable RGB and hot-swappable switches.',
    price: 129.99,
    category: 'Electronics',
    image: 'https://picsum.photos/seed/keyboard/600/600',
    rating: 4.6,
    reviews: 210,
  },
  {
    id: '5',
    name: 'Solaris Sunglasses',
    description: 'Polarized lenses with titanium frames for weightless protection.',
    price: 155.00,
    category: 'Fashion',
    image: 'https://picsum.photos/seed/shades/600/600',
    rating: 4.5,
    reviews: 340,
  },
  {
    id: '6',
    name: 'Cloud Running Shoes',
    description: 'Lightweight cushioning for maximum performance on any terrain.',
    price: 140.00,
    category: 'Fashion',
    image: 'https://picsum.photos/seed/shoes/600/600',
    rating: 4.8,
    reviews: 760,
  },
];
